id: A6A77082D
title: Aspirations in Accordance with the Dharma
type: translation
pechas:
- IC4377353
- IB1FB7F1A
- I07CA55CF
- I3FEA61BA
- ID36A352A
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:41:14.549108
  last_modified_at: 2023-01-04 11:41:14.549120
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  IC4377353/FF1C: 5EE9
  IB1FB7F1A/266C: 5EE9
  I07CA55CF/47A0: 5EE9
  I3FEA61BA/7AEA: 5EE9
  ID36A352A/F6BF: 5EE9
